# Generated by Django 4.0.1 on 2022-02-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Woman',
            new_name='Women',
        ),
    ]
